# We use poetry to run formatting and linting before commit/push
# Longer checks such as tests, security and complexity baseline
# are run as part of CI to prevent slower feedback loop
# All checks can be run locally via `make pr`

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0" # v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-toml
        files: \.py$
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: '\.(py|pyw)$'
        exclude: '\.venv/|\.git/|\.tox/'
        args: ['--config=.flake8']

